# config.yaml
#
# The program looks for config file first in ~/.config/giosifier/config.yaml, then in /etc/giosifier/config.yaml, in this order.
#
# Default alerts taken from: https://powietrze.gios.gov.pl/pjp/content/annual_assessment_air_acceptable_level
station:
  id: "20488" #Example station ID for Warsaw, Solidarno≈õci

pm10:
  alert: 40

no2:
  alert: 200

# ntfy config
# You can use public or custom ntfy server
# If you use basic Token authentication, uncomment auth and provide your auth method
# Eg. for basic auth token it would be:
#   auth: "Basic [token]"
ntfy:
  url: "https://ntfy.sh/mytopic"
  #auth: ""