name: Build Binary with Niutka (x86_64)

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build in container
        run: |
          docker run --rm --platform linux/amd64 -v ${{ github.workspace }}:/src -w /src python:3.13.5 /bin/bash -c " \
          apt-get update && apt-get install -y build-essential libffi-dev libzstd-dev gcc patchelf &&\
          pip install nuitka requests pyyaml pyjson zstandard setuptools && \
          python3 -m nuitka \
          --onefile \
          --standalone \
          --output-filename=giosifier-x86_64 \
          main.py"
        
      - name: Push binary
        uses: actions/upload-artifact@v4
        with:
          name: giosifier-x86_64
          path: giosifier-x86_64
