name: Build Binary with Nuitka (arm/v7)

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - '!.github/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build in container
        run: |
          docker run --rm --platform linux/arm/v7 -v ${{ github.workspace }}:/src -w /src python:3.14.3 /bin/bash -c " \
          apt-get update && apt-get install -y build-essential libffi-dev libzstd-dev gcc patchelf &&\
          pip install nuitka requests pyyaml pyjson setuptools && \
          python3 -m nuitka \
          --onefile \
          --standalone \
          --jobs=1 \
          --output-filename=giosifier-armv7 \
          main.py"
        
      - name: Push binary
        uses: actions/upload-artifact@v4
        with:
          name: giosifier-armv7
          path: giosifier-armv7
