name: Build Binary with Nuitka (x86_64)

on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - '!.github/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build in container
        run: |
          docker run --rm --platform linux/amd64 -v ${{ github.workspace }}:/src -w /src python:3.14.3 /bin/bash -c " \
          apt-get update && apt-get install -y build-essential gcc patchelf &&\
          pip install nuitka requests pyyaml pyjson setuptools && \
          python3 -m nuitka \
          --standalone \
          --output-filename=giosifier \
          main.py"
          mv main.dist giosifier-x86_64
          tar -czf giosifier-x86_64.tar.gz giosifier-x86_64/
        
      - name: Push binary
        uses: actions/upload-artifact@v4
        with:
          name: giosifier-x86_64-release
          path: giosifier-x86_64.tar.gz
